### ISSUE TITLE
Google Fit integration?

### ISSUE THREAD

**Issue by barakplasma** [unrelatedlabs/infection-alert#1]
Hi there,

Would you be interested in a Google Fit integration?

There's access to a user's heart rate via https://developers.google.com/fit/datatypes/body#heart_rate .
I imagine we could get a user's permission for their heart rate data, and upload it to the same Google BigQuery database.

**Comment by unrelatedlabs** [comment]
Could use the same backend yes. but the app would need to be written from scratch?
