### ISSUE TITLE
Walkthrough on how to build in Xcode would be useful

### ISSUE THREAD

**Issue by jeffehobbs** [unrelatedlabs/infection-alert#3]
A step-by-step "how to" explaining how to build this project would greatly increase adoption.

**Comment by unrelatedlabs** [comment]
Open in Xcode, change the Team and bundle id. build

**Comment by jeffehobbs** [comment]
Requires cocoapods?

**Comment by unrelatedlabs** [comment]
yes, sorry i forgot about that.
install cooapods than 

    pod install
    open Infection\ Alert.xcworkspace

**Comment by jeffehobbs** [comment]
Thank you! Almost there, one critical error left; during build, I get this error:

`error: /Users/userhome/Desktop/infection-alert-master/ios/Infection Alert/cert: No such file or directory (in target 'Infection Alert' from project 'Infection Alert')`

**Comment by unrelatedlabs** [comment]
Maybe the cert folder is missing. There should be an empty "cert" folder  at `ios/Infection Alert/cert`

**Comment by jeffehobbs** [comment]
That was it! After creating that folder, it's building. Thanks!
